# Import Library

In [ ]:
import re 
import string
import pandas as pd
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

# Import Dataset

In [ ]:
df = pd.read_csv("yelp_labelled.csv")
df.head()

,Wow... Loved this place.,1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,Crust is not good.,0,NaN,NaN,NaN,NaN
1,Not tasty and the texture was just nasty.,0,NaN,NaN,NaN,NaN
2,Stopped by during the late May bank holiday of...,1,NaN,NaN,NaN,NaN
3,The selection on the menu was great and so wer...,1,NaN,NaN,NaN,NaN
4,Now I am getting angry and I want my damn pho.,0,NaN,NaN,NaN,NaN

In [ ]:
df.drop(['1','Unnamed: 2','Unnamed: 3','Unnamed: 4','Unnamed: 5'], axis=1, inplace=True)

In [ ]:
nameDict={"Wow... Loved this place.":"Review"}
df=df.rename(columns=nameDict)

In [ ]:
df.head()

                                              Review
0                                 Crust is not good.
1          Not tasty and the texture was just nasty.
2  Stopped by during the late May bank holiday of...
3  The selection on the menu was great and so wer...
4     Now I am getting angry and I want my damn pho.

# Case Folding and Removing

In [ ]:
df['Review'] = df['Review'].str.lower()
df.head()

                                              Review
0                                 crust is not good.
1          not tasty and the texture was just nasty.
2  stopped by during the late may bank holiday of...
3  the selection on the menu was great and so wer...
4     now i am getting angry and i want my damn pho.

In [ ]:
df['Review'] = df['Review'].str.replace(r'\d+', '', regex=True)
df.head()

                                              Review
0                                 crust is not good.
1          not tasty and the texture was just nasty.
2  stopped by during the late may bank holiday of...
3  the selection on the menu was great and so wer...
4     now i am getting angry and i want my damn pho.

In [ ]:
df['Review'] = df['Review'].str.replace(r'[!”#$%&’()*+,-./:;<=>?@[\]^_`{|}~]', '', regex=True)
df.head()

                                              Review
0                                  crust is not good
1           not tasty and the texture was just nasty
2  stopped by during the late may bank holiday of...
3  the selection on the menu was great and so wer...
4      now i am getting angry and i want my damn pho

# Filtering

In [ ]:
text = stopwords.words('english')
df['Review'] = df['Review'].apply(lambda x: ' '.join([word for word in x.split()if word not in (text)]))
df.head()

                                              Review
0                                         crust good
1                                tasty texture nasty
2  stopped late may bank holiday rick steve recom...
3                        selection menu great prices
4                        getting angry want damn pho